# backend/Dockerfile.dev

FROM python:3.11-slim

# Sistem gereksinimleri
RUN apt-get update && apt-get install -y build-essential

# Çalışma dizini
WORKDIR /app

# Gerekli dosyaları kopyala
COPY backend/api /app/api
COPY backend/requirements.txt /app/requirements.txt

# Paketleri kur
RUN pip install --upgrade pip && pip install -r requirements.txt

# Uygulamayı başlat
CMD ["uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8020", "--reload"]
