# Geliştirme için node imajı
FROM node:18

# Uygulama dizinine geç
WORKDIR /app

# package.json ve varsa lock dosyasını kopyala
COPY package.json ./
COPY package-lock.json ./

# Bağımlılıkları yükle
RUN npm install

# Diğer tüm dosyaları kopyala
COPY . .

# Geliştirme sunucusunu başlat
CMD ["npm", "start"]
